/***
*Class            IssueService_Test 
*Author           Godfrey Mwamsoyo
*Story            S-40895
*Date             12/24/2017
*Description      Test class for Issue Service classes
-----------------------------Modifications Updates ------------------------------
*Date             
*Description      

***/
@isTest(SeeAllData=false)
private class IssueService_Test {
    @testSetup
    static void setup()
    {
    }
       
    static testMethod void happyPathCreateIssueTest() 
    {   
    }
    
    static testMethod void missingRequiredAttributeTest() 
    {   
    }
    
    static testMethod void exceptionTest() 
    {   
    }
}